#!/usr/bin/env bash
# Generate agent/.env for local development from the deployed agent stack's
# Terraform outputs.  Usage:  source scripts/init-env.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF="terraform -chdir=${REPO_ROOT}/iac/agent"

get() { $TF output -raw "$1" 2>/dev/null || echo ""; }

PROJECT_ID="$(get project_a_id)"
REGION="$(get region)"
ENGINE_ID="$(get reasoning_engine_id)"
ENGINE_NAME="$(get reasoning_engine_resource_name)"
MEMORY_BANK="$(get memory_bank_resource_name)"
EVIDENCE_BUCKET="$(get evidence_bucket_name)"
CUSTOM_MCP_URL="$(get custom_mcp_url)"

cat > "${REPO_ROOT}/agent/.env" <<EOF
# Generated by scripts/init-env.sh from Terraform outputs. Do not commit.
PROJECT_ID=${PROJECT_ID}
REGION=${REGION}
GEMINI_MODEL=gemini-2.5-flash
GKE_REMOTE_MCP_URL=https://container.googleapis.com/mcp/read-only
K8S_MCP_URL=${CUSTOM_MCP_URL}
EVIDENCE_BUCKET=${EVIDENCE_BUCKET}
MEMORY_BANK_RESOURCE=${MEMORY_BANK}
AGENT_RESOURCE_NAME=${ENGINE_NAME}
EOF

# Also export the two vars invoke_agent.py needs, into the current shell.
export PROJECT_ID REGION
export REASONING_ENGINE_ID="${ENGINE_ID}"

echo "Wrote ${REPO_ROOT}/agent/.env and exported PROJECT_ID / REGION / REASONING_ENGINE_ID"
